language: node_js
node_js:
  - '10.4.1'
  - '10'
cache:
  yarn: true
  directories:
  - node_modules
script: skip
deploy:
  - provider: npm
    email: iturgeon+npm2@gmail.com
    node_js: '10.4.1'
    script: skip
    before_deploy:
      - cd packages/app/obojobo-express
      - yarn build
    after_deploy:
      - cd ../../..
    on:
      tags: true
      # only matches when a semver tag is found
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
    api_key:
      secure: "en1lFaIHzet1sqqaVf2HlLyGcXnG0qx+1Sa4vGIxC65FrUftOBqBMcGZZ4FFAOavZKSLHgQuSXzERc6Oe0QAicbn/OkEoIp9gZUyIaovwHk4SrNI8JFWpTFwywieevcD8MKgbyHjP2HdzhNY5PuG8OXnvKHKudhZal4FTE9x/VG8UhlKfAfuu28fVYia9muAgOGUI/YlEzY9QKMyNoUryo1aP0HOntnm4vBy7JvUW2MUG70YLqJ0tOy5Pp7UuFdDmLP9jq6n/NMovpJyfrnBXil2gvEp8c285H0E6X49PpnX3VwQigv5O7WxD06VbH7ch7ugy6FE7vGPGlaxwGFC3MtTKIP2PCefSv+PZ6tKi/11gEzWFr2o2yZAneO5BkIF7fZCji3tQaPTpIsHmrBdcbrMcamHEB/KCl5MjMTKTMegEOv9YJHvVDzjesjWMkf5aBOgiL4N7F6vdHXNluRrNtm3DPXWnx3jmgURC4yp+l6VsCtW2AGDCjqynT3JU+ThEK4Z8SiNtsNXvzZLJd9MvDu5F5WtSmm+G8ScW7dynK4sdpVyNyAbrmVpX3PDZVeoWkS045jiGrKzcLtnlDEpBzp5LpRLhD9G3JTRAkF78PIXEsCSUsNgR5pkgXhStRrErvUcEnbpB7iIN4HvSYxA104GT6emlCBO6nlsLtEB4YA="
  - provider: npm
    email: iturgeon+npm2@gmail.com
    node_js: '10.4.1'
    script: skip
    before_deploy:
      - cd packages/app/obojobo-document-engine
    after_deploy:
      - cd ../../..
    on:
      tags: true
      # only matches when a semver tag is found
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
    api_key:
      secure: "en1lFaIHzet1sqqaVf2HlLyGcXnG0qx+1Sa4vGIxC65FrUftOBqBMcGZZ4FFAOavZKSLHgQuSXzERc6Oe0QAicbn/OkEoIp9gZUyIaovwHk4SrNI8JFWpTFwywieevcD8MKgbyHjP2HdzhNY5PuG8OXnvKHKudhZal4FTE9x/VG8UhlKfAfuu28fVYia9muAgOGUI/YlEzY9QKMyNoUryo1aP0HOntnm4vBy7JvUW2MUG70YLqJ0tOy5Pp7UuFdDmLP9jq6n/NMovpJyfrnBXil2gvEp8c285H0E6X49PpnX3VwQigv5O7WxD06VbH7ch7ugy6FE7vGPGlaxwGFC3MtTKIP2PCefSv+PZ6tKi/11gEzWFr2o2yZAneO5BkIF7fZCji3tQaPTpIsHmrBdcbrMcamHEB/KCl5MjMTKTMegEOv9YJHvVDzjesjWMkf5aBOgiL4N7F6vdHXNluRrNtm3DPXWnx3jmgURC4yp+l6VsCtW2AGDCjqynT3JU+ThEK4Z8SiNtsNXvzZLJd9MvDu5F5WtSmm+G8ScW7dynK4sdpVyNyAbrmVpX3PDZVeoWkS045jiGrKzcLtnlDEpBzp5LpRLhD9G3JTRAkF78PIXEsCSUsNgR5pkgXhStRrErvUcEnbpB7iIN4HvSYxA104GT6emlCBO6nlsLtEB4YA="
  - provider: npm
    email: iturgeon+npm2@gmail.com
    node_js: '10.4.1'
    script: skip
    before_deploy:
      - cd packages/app/obojobo-document-xml-parser
    after_deploy:
      - cd ../../..
    on:
      tags: true
      # only matches when a semver tag is found
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
    api_key:
      secure: "en1lFaIHzet1sqqaVf2HlLyGcXnG0qx+1Sa4vGIxC65FrUftOBqBMcGZZ4FFAOavZKSLHgQuSXzERc6Oe0QAicbn/OkEoIp9gZUyIaovwHk4SrNI8JFWpTFwywieevcD8MKgbyHjP2HdzhNY5PuG8OXnvKHKudhZal4FTE9x/VG8UhlKfAfuu28fVYia9muAgOGUI/YlEzY9QKMyNoUryo1aP0HOntnm4vBy7JvUW2MUG70YLqJ0tOy5Pp7UuFdDmLP9jq6n/NMovpJyfrnBXil2gvEp8c285H0E6X49PpnX3VwQigv5O7WxD06VbH7ch7ugy6FE7vGPGlaxwGFC3MtTKIP2PCefSv+PZ6tKi/11gEzWFr2o2yZAneO5BkIF7fZCji3tQaPTpIsHmrBdcbrMcamHEB/KCl5MjMTKTMegEOv9YJHvVDzjesjWMkf5aBOgiL4N7F6vdHXNluRrNtm3DPXWnx3jmgURC4yp+l6VsCtW2AGDCjqynT3JU+ThEK4Z8SiNtsNXvzZLJd9MvDu5F5WtSmm+G8ScW7dynK4sdpVyNyAbrmVpX3PDZVeoWkS045jiGrKzcLtnlDEpBzp5LpRLhD9G3JTRAkF78PIXEsCSUsNgR5pkgXhStRrErvUcEnbpB7iIN4HvSYxA104GT6emlCBO6nlsLtEB4YA="
